//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace WebTest.TestLib
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class SqlSugarTestEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“SqlSugarTestEntities”部分中的连接字符串初始化新 SqlSugarTestEntities 对象。
        /// </summary>
        public SqlSugarTestEntities() : base("name=SqlSugarTestEntities", "SqlSugarTestEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 SqlSugarTestEntities 对象。
        /// </summary>
        public SqlSugarTestEntities(string connectionString) : base(connectionString, "SqlSugarTestEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 SqlSugarTestEntities 对象。
        /// </summary>
        public SqlSugarTestEntities(EntityConnection connection) : base(connection, "SqlSugarTestEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<School> School
        {
            get
            {
                if ((_School == null))
                {
                    _School = base.CreateObjectSet<School>("School");
                }
                return _School;
            }
        }
        private ObjectSet<School> _School;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Student> Student
        {
            get
            {
                if ((_Student == null))
                {
                    _Student = base.CreateObjectSet<Student>("Student");
                }
                return _Student;
            }
        }
        private ObjectSet<Student> _Student;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Subject> Subject
        {
            get
            {
                if ((_Subject == null))
                {
                    _Subject = base.CreateObjectSet<Subject>("Subject");
                }
                return _Subject;
            }
        }
        private ObjectSet<Subject> _Subject;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<InsertTest> InsertTests
        {
            get
            {
                if ((_InsertTests == null))
                {
                    _InsertTests = base.CreateObjectSet<InsertTest>("InsertTests");
                }
                return _InsertTests;
            }
        }
        private ObjectSet<InsertTest> _InsertTests;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<GuidTest> GuidTests
        {
            get
            {
                if ((_GuidTests == null))
                {
                    _GuidTests = base.CreateObjectSet<GuidTest>("GuidTests");
                }
                return _GuidTests;
            }
        }
        private ObjectSet<GuidTest> _GuidTests;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<TableDataTypeTest> TableDataTypeTests
        {
            get
            {
                if ((_TableDataTypeTests == null))
                {
                    _TableDataTypeTests = base.CreateObjectSet<TableDataTypeTest>("TableDataTypeTests");
                }
                return _TableDataTypeTests;
            }
        }
        private ObjectSet<TableDataTypeTest> _TableDataTypeTests;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<TestOfNull> TestOfNulls
        {
            get
            {
                if ((_TestOfNulls == null))
                {
                    _TestOfNulls = base.CreateObjectSet<TestOfNull>("TestOfNulls");
                }
                return _TestOfNulls;
            }
        }
        private ObjectSet<TestOfNull> _TestOfNulls;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 School EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToSchool(School school)
        {
            base.AddObject("School", school);
        }
    
        /// <summary>
        /// 用于向 Student EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToStudent(Student student)
        {
            base.AddObject("Student", student);
        }
    
        /// <summary>
        /// 用于向 Subject EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToSubject(Subject subject)
        {
            base.AddObject("Subject", subject);
        }
    
        /// <summary>
        /// 用于向 InsertTests EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToInsertTests(InsertTest insertTest)
        {
            base.AddObject("InsertTests", insertTest);
        }
    
        /// <summary>
        /// 用于向 GuidTests EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToGuidTests(GuidTest guidTest)
        {
            base.AddObject("GuidTests", guidTest);
        }
    
        /// <summary>
        /// 用于向 TableDataTypeTests EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToTableDataTypeTests(TableDataTypeTest tableDataTypeTest)
        {
            base.AddObject("TableDataTypeTests", tableDataTypeTest);
        }
    
        /// <summary>
        /// 用于向 TestOfNulls EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToTestOfNulls(TestOfNull testOfNull)
        {
            base.AddObject("TestOfNulls", testOfNull);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SqlSugarTestModel", Name="GuidTest")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GuidTest : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 GuidTest 对象。
        /// </summary>
        /// <param name="gUID">GUID 属性的初始值。</param>
        public static GuidTest CreateGuidTest(global::System.Guid gUID)
        {
            GuidTest guidTest = new GuidTest();
            guidTest.GUID = gUID;
            return guidTest;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid GUID
        {
            get
            {
                return _GUID;
            }
            set
            {
                if (_GUID != value)
                {
                    OnGUIDChanging(value);
                    ReportPropertyChanging("GUID");
                    _GUID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("GUID");
                    OnGUIDChanged();
                }
            }
        }
        private global::System.Guid _GUID;
        partial void OnGUIDChanging(global::System.Guid value);
        partial void OnGUIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SqlSugarTestModel", Name="InsertTest")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class InsertTest : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 InsertTest 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static InsertTest CreateInsertTest(global::System.Int32 id)
        {
            InsertTest insertTest = new InsertTest();
            insertTest.id = id;
            return insertTest;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String v1
        {
            get
            {
                return _v1;
            }
            set
            {
                Onv1Changing(value);
                ReportPropertyChanging("v1");
                _v1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("v1");
                Onv1Changed();
            }
        }
        private global::System.String _v1;
        partial void Onv1Changing(global::System.String value);
        partial void Onv1Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String v2
        {
            get
            {
                return _v2;
            }
            set
            {
                Onv2Changing(value);
                ReportPropertyChanging("v2");
                _v2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("v2");
                Onv2Changed();
            }
        }
        private global::System.String _v2;
        partial void Onv2Changing(global::System.String value);
        partial void Onv2Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String v3
        {
            get
            {
                return _v3;
            }
            set
            {
                Onv3Changing(value);
                ReportPropertyChanging("v3");
                _v3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("v3");
                Onv3Changed();
            }
        }
        private global::System.String _v3;
        partial void Onv3Changing(global::System.String value);
        partial void Onv3Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> int1
        {
            get
            {
                return _int1;
            }
            set
            {
                Onint1Changing(value);
                ReportPropertyChanging("int1");
                _int1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("int1");
                Onint1Changed();
            }
        }
        private Nullable<global::System.Int32> _int1;
        partial void Onint1Changing(Nullable<global::System.Int32> value);
        partial void Onint1Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> d1
        {
            get
            {
                return _d1;
            }
            set
            {
                Ond1Changing(value);
                ReportPropertyChanging("d1");
                _d1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("d1");
                Ond1Changed();
            }
        }
        private Nullable<global::System.DateTime> _d1;
        partial void Ond1Changing(Nullable<global::System.DateTime> value);
        partial void Ond1Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String txt
        {
            get
            {
                return _txt;
            }
            set
            {
                OntxtChanging(value);
                ReportPropertyChanging("txt");
                _txt = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("txt");
                OntxtChanged();
            }
        }
        private global::System.String _txt;
        partial void OntxtChanging(global::System.String value);
        partial void OntxtChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SqlSugarTestModel", Name="School")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class School : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 School 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static School CreateSchool(global::System.Int32 id)
        {
            School school = new School();
            school.id = id;
            return school;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SqlSugarTestModel", Name="Student")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Student : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Student 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static Student CreateStudent(global::System.Int32 id)
        {
            Student student = new Student();
            student.id = id;
            return student;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> sch_id
        {
            get
            {
                return _sch_id;
            }
            set
            {
                Onsch_idChanging(value);
                ReportPropertyChanging("sch_id");
                _sch_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sch_id");
                Onsch_idChanged();
            }
        }
        private Nullable<global::System.Int32> _sch_id;
        partial void Onsch_idChanging(Nullable<global::System.Int32> value);
        partial void Onsch_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sex
        {
            get
            {
                return _sex;
            }
            set
            {
                OnsexChanging(value);
                ReportPropertyChanging("sex");
                _sex = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sex");
                OnsexChanged();
            }
        }
        private global::System.String _sex;
        partial void OnsexChanging(global::System.String value);
        partial void OnsexChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> isOk
        {
            get
            {
                return _isOk;
            }
            set
            {
                OnisOkChanging(value);
                ReportPropertyChanging("isOk");
                _isOk = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isOk");
                OnisOkChanged();
            }
        }
        private Nullable<global::System.Boolean> _isOk;
        partial void OnisOkChanging(Nullable<global::System.Boolean> value);
        partial void OnisOkChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SqlSugarTestModel", Name="Subject")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Subject : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Subject 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static Subject CreateSubject(global::System.Int32 id)
        {
            Subject subject = new Subject();
            subject.id = id;
            return subject;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> sid
        {
            get
            {
                return _sid;
            }
            set
            {
                OnsidChanging(value);
                ReportPropertyChanging("sid");
                _sid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sid");
                OnsidChanged();
            }
        }
        private Nullable<global::System.Int32> _sid;
        partial void OnsidChanging(Nullable<global::System.Int32> value);
        partial void OnsidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SqlSugarTestModel", Name="TableDataTypeTest")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TableDataTypeTest : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 TableDataTypeTest 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        public static TableDataTypeTest CreateTableDataTypeTest(global::System.Byte id)
        {
            TableDataTypeTest tableDataTypeTest = new TableDataTypeTest();
            tableDataTypeTest.Id = id;
            return tableDataTypeTest;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Byte _Id;
        partial void OnIdChanging(global::System.Byte value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SqlSugarTestModel", Name="TestOfNull")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TestOfNull : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 TestOfNull 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static TestOfNull CreateTestOfNull(global::System.Int32 id)
        {
            TestOfNull testOfNull = new TestOfNull();
            testOfNull.id = id;
            return testOfNull;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> createDate
        {
            get
            {
                return _createDate;
            }
            set
            {
                OncreateDateChanging(value);
                ReportPropertyChanging("createDate");
                _createDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createDate");
                OncreateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _createDate;
        partial void OncreateDateChanging(Nullable<global::System.DateTime> value);
        partial void OncreateDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] bytes
        {
            get
            {
                return StructuralObject.GetValidValue(_bytes);
            }
            set
            {
                OnbytesChanging(value);
                ReportPropertyChanging("bytes");
                _bytes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("bytes");
                OnbytesChanged();
            }
        }
        private global::System.Byte[] _bytes;
        partial void OnbytesChanging(global::System.Byte[] value);
        partial void OnbytesChanged();

        #endregion

    
    }

    #endregion

    
}
