USE [master]
GO
/****** Object:  Database [SQLSUGARBIGTEST11]    Script Date: 2015/12/17 16:19:17 ******/
CREATE DATABASE [SQLSUGARBIGTEST11]
 
ALTER DATABASE [SQLSUGARBIGTEST11] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SQLSUGARBIGTEST11].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SQLSUGARBIGTEST11] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SQLSUGARBIGTEST11] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SQLSUGARBIGTEST11] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SQLSUGARBIGTEST11] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SQLSUGARBIGTEST11] SET ARITHABORT OFF 
GO
ALTER DATABASE [SQLSUGARBIGTEST11] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SQLSUGARBIGTEST11] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SQLSUGARBIGTEST11] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SQLSUGARBIGTEST11] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SQLSUGARBIGTEST11] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SQLSUGARBIGTEST11] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SQLSUGARBIGTEST11] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SQLSUGARBIGTEST11] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SQLSUGARBIGTEST11] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SQLSUGARBIGTEST11] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SQLSUGARBIGTEST11] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SQLSUGARBIGTEST11] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SQLSUGARBIGTEST11] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [SQLSUGARBIGTEST11] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [SQLSUGARBIGTEST11] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SQLSUGARBIGTEST11] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SQLSUGARBIGTEST11] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [SQLSUGARBIGTEST11] SET RECOVERY FULL 
GO
ALTER DATABASE [SQLSUGARBIGTEST11] SET  MULTI_USER 
GO
ALTER DATABASE [SQLSUGARBIGTEST11] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SQLSUGARBIGTEST11] SET DB_CHAINING OFF 
GO
ALTER DATABASE [SQLSUGARBIGTEST11] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [SQLSUGARBIGTEST11] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [SQLSUGARBIGTEST11] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'SQLSUGARBIGTEST11', N'ON'
GO
USE [SQLSUGARBIGTEST11]
GO
/****** Object:  FullTextCatalog [catalog]    Script Date: 2015/12/17 16:19:17 ******/
CREATE FULLTEXT CATALOG [catalog]WITH ACCENT_SENSITIVITY = ON

GO
/****** Object:  Table [dbo].[student]    Script Date: 2015/12/17 16:19:17 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[student](
	[id] [uniqueidentifier] NOT NULL,
	[name] [varchar](50) NULL,
	[createTime] [datetime] NULL,
	[num] [int] NULL,
 CONSTRAINT [PK_student] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Index [student_index]    Script Date: 2015/12/17 16:19:17 ******/
CREATE UNIQUE NONCLUSTERED INDEX [student_index] ON [dbo].[student]
(
	[num] ASC,
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [student_index2]    Script Date: 2015/12/17 16:19:17 ******/
CREATE UNIQUE NONCLUSTERED INDEX [student_index2] ON [dbo].[student]
(
	[num] DESC,
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [SQLSUGARBIGTEST11] SET  READ_WRITE 
GO
