using SqlSugar;
using OrmTest;
_1_CodeFirst.Init();
_2_DbFirst.Init();
_3_EasyQuery.Init();
_4_JoinQuery.Init();
_5_PageQuery.Init();
_a7_JsonType.Init();
Console.WriteLine("DEMO执行完成");
Console.Read();
