using SqlSugar;
using OrmTest;
_1_CodeFirst.Init();
_2_DbFirst.Init();
_3_EasyQuery.Init();
_4_JoinQuery.Init();
_4_Subquery.Init();
_5_PageQuery.Init();
_6_NavQuery.Init();
_7_GroupQuery.Init();
_8_Insert.Init();
_9_Update.Init();
_a1_Delete.Init();
_a2_Sql.Init();
_a3_Merge.Init();
//_a4_SplitTable.Init();
_a5_GridSave.Init();
_a6_SqlPage.Init();
_a7_JsonType.Init();
_a8_SelectReturnType.Init();
Console.WriteLine("DEMO执行完成");
Console.Read();
